import { z } from 'zod'

const idSchema = z.union([z.string().uuid(), z.string().min(1).max(200), z.number().int().nonnegative()])
const optionalId = idSchema.nullable().optional()
const timestampSchema = z.string().datetime().optional()
const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()
const text = (max = 4000) => z.string().trim().max(max)
const tagsSchema = z.array(text(64)).max(50)
const record = (shape) => z.object({ id: idSchema.optional(), ...shape, created_at: timestampSchema, updated_at: timestampSchema }).passthrough()
const patch = (schema) => schema.omit({ id: true, user_id: true, created_at: true }).partial().strict().refine((value) => Object.keys(value).length > 0, 'At least one field is required.')

export const userSchema = record({ email: z.string().email().max(254), user_metadata: z.record(z.unknown()).optional() })
export const userProfileSchema = record({ user_id: idSchema, display_name: text(120).nullable().optional(), avatar_url: z.string().url().nullable().optional(), bio: text(1000).nullable().optional() })
export const taskSchema = record({ user_id: idSchema, title: text(200).min(1), description: text().default(''), due_date: dateSchema.nullable(), estimated_duration: z.number().int().min(0).max(1440).default(30), is_essential: z.boolean().default(false), completed: z.boolean().default(false), status: z.enum(['active', 'completed', 'cancelled']).optional(), completed_at: timestampSchema.nullable(), mode: text(64).nullable().optional(), project_id: optionalId, category: text(100).nullable().optional(), tags: tagsSchema.default([]) })
export const projectSchema = record({ user_id: idSchema, title: text(200).min(1), description: text().default(''), color: text(32).default('blue'), icon: text(16).default('📁'), status: z.enum(['active', 'completed', 'archived']).default('active'), goal: text(2000).default(''), target_date: dateSchema.nullable(), mode: text(64).nullable().optional(), category: text(100).nullable().optional(), tags: tagsSchema.default([]), order_index: z.number().int().min(0).default(0) })
export const subtaskSchema = record({ user_id: idSchema, task_id: idSchema, title: text(200).min(1), description: text().default(''), estimated_duration: z.number().int().min(0).max(1440).nullable().optional(), is_completed: z.boolean().default(false), completed_at: timestampSchema.nullable(), order_index: z.number().int().min(0).default(0) })
export const routineSchema = record({ user_id: idSchema, name: text(200).min(1), description: text().default(''), repeat_pattern: z.enum(['daily', 'weekdays', 'weekly', 'custom']).default('daily'), is_active: z.boolean().default(true), mode: text(64).nullable().optional(), category: text(100).nullable().optional(), tags: tagsSchema.default([]) })
export const routineStepSchema = record({ user_id: idSchema, routine_id: idSchema, name: text(200).min(1), description: text().default(''), duration_minutes: z.number().int().min(0).max(1440), order_index: z.number().int().min(0), is_essential: z.boolean().default(false), preferred_time: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable().optional() })
export const houseworkTaskSchema = record({ user_id: idSchema, task_type: z.literal('housework'), title: text(200).min(1), description: text().default(''), room: text(100).min(1), frequency: z.enum(['daily', 'every_2_days', 'twice_weekly', 'weekly', 'biweekly', 'monthly', 'quarterly', 'seasonal']), estimated_duration: z.number().int().min(0).max(1440).default(30), prep_time: z.number().int().min(0).max(1440).default(0), cleanup_time: z.number().int().min(0).max(1440).default(0), checklist: z.array(text(300)).max(100).default([]), required_items: z.array(text(300)).max(100).default([]), is_essential: z.boolean().default(false), is_active: z.boolean().default(true), mode: z.literal('home'), next_due_date: z.string().datetime(), last_completed: timestampSchema.nullable(), completion_count: z.number().int().min(0).default(0) })
export const inboxItemSchema = record({ user_id: idSchema, content: text(4000).min(1), category: text(100).nullable().optional(), status: z.enum(['captured', 'processed', 'archived']).default('captured') })
export const userPreferencesSchema = record({ user_id: idSchema, wake_time: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), sleep_time: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), work_start_time: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable(), work_end_time: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable(), theme: z.enum(['light', 'dark', 'low-stim']), notifications_enabled: z.boolean() })
export const modulePreferencesSchema = z.object({ theme: z.enum(['default', 'light', 'dark', 'low-stim']).default('default'), viewMode: z.enum(['detailed', 'compact']).default('detailed'), showAnimations: z.boolean().default(true), showNotifications: z.boolean().default(true), sortBy: z.enum(['priority', 'due_date', 'created_at']).default('priority'), hideCompleted: z.boolean().default(false) }).strict()

export const accessibilityPreferencesSchema = z.object({ fontSize: z.enum(['small', 'medium', 'large', 'xlarge']), contrast: z.enum(['normal', 'high']), reduceMotion: z.boolean(), soundEffects: z.boolean(), focusMode: z.boolean(), dyslexicFont: z.boolean(), lineSpacing: z.enum(['normal', 'relaxed', 'loose']), colorBlindMode: z.enum(['none', 'protanopia', 'deuteranopia', 'tritanopia']) }).strict()
export const onboardingPreferencesSchema = z.object({ showEncouragement: z.boolean(), enableSoundEffects: z.boolean(), useTimers: z.boolean(), breakReminders: z.boolean(), celebrateSmallWins: z.boolean() }).strict()
export const onboardingDataSchema = z.object({ selectedRoles: z.array(text(64)).max(50), customRoles: z.array(text(120)).max(50), enabledModules: z.array(z.enum(['tasks', 'routines', 'housework', 'timeline', 'habits', 'inbox'])).min(2), uiStyle: z.enum(['visual', 'minimal', 'gamified']), preferences: onboardingPreferencesSchema, progress: z.object({ currentStep: z.number().int().min(0).max(6), totalSteps: z.number().int().min(1).max(6), completedSteps: z.array(text(32)).max(6), isComplete: z.boolean() }).strict(), updatedAt: timestampSchema, completedAt: timestampSchema, skippedSteps: z.array(text(32)).max(6).optional() }).passthrough()
export const routineSessionSchema = record({ user_id: idSchema, routine_id: idSchema, routine_name: text(200), started_at: z.string().datetime(), current_step_index: z.number().int().min(0), completed_steps: z.array(z.object({ step_index: z.number().int().min(0), step_id: idSchema, skipped: z.boolean().optional(), completed_at: z.string().datetime() }).strict()), status: z.enum(['in_progress', 'completed', 'cancelled']), total_steps: z.number().int().min(0), completed_at: timestampSchema.nullable(), cancelled_at: timestampSchema.nullable() })
export const houseworkCompletionSchema = record({ user_id: idSchema, task_id: idSchema, completed_at: z.string().datetime(), checklist_completed: z.array(z.unknown()), duration_actual: z.number().min(0).nullable() })

export const domainSchemasByCollection = Object.freeze({ 'user-preferences': userPreferencesSchema, tasks: taskSchema, projects: projectSchema, subtasks: subtaskSchema, routines: routineSchema, 'routine-steps': routineStepSchema, 'routine-sessions': routineSessionSchema, 'housework-tasks': houseworkTaskSchema, 'housework-completions': houseworkCompletionSchema, 'inbox-items': inboxItemSchema })
export const domainCreateSchemasByCollection = Object.freeze(Object.fromEntries(Object.entries(domainSchemasByCollection).map(([name, schema]) => [name, schema.strict()])))
export const domainPatchSchemasByCollection = Object.freeze(Object.fromEntries(Object.entries(domainSchemasByCollection).map(([name, schema]) => [name, patch(schema)])))
export const parseDomain = (schema, value) => schema.parse(value)

